export const mockData = [
  {
    id: 1,
    name: "Prabhat Ranjan",
    age: 31,
    address: "Shahdara",
    occupation: "Student",
  },
  {
    id: 2,
    name: "Prabhat Ranjan",
    age: 31,
    address: "Shahdara",
    occupation: "Student",
  },
  {
    id: 3,
    name: "Prabhat",
    age: 31,
    address: "Shahdara",
    occupation: "Student",
  },
  {
    id: 4,
    name: "Prabhat Ranjan",
    age: 31,
    address: "Shahdara",
    occupation: "Student",
  },
  {
    id: 5,
    name: "Prabhat Ranjan",
    age: 31,
    address: "Shahdara",
    occupation: "Student",
  },
  {
    id: 6,
    name: "Prabhat Ranjan",
    age: 31,
    address: "Shahdara",
    occupation: "Student",
  },
  {
    id: 7,
    name: "Prabhat Ranjan",
    age: 31,
    address: "Shahdara",
    occupation: "Student",
  },
  {
    id: 8,
    name: "Prabhat Ranjan",
    age: 31,
    address: "Shahdara",
    occupation: "Student",
  },
  {
    id: 9,
    name: "Vaurn ",
    age: 31,
    address: "Shahdara Delhi",
    occupation: "Frontend",
  },
  {
    id: 10,
    name: "Prabhat Ranjan",
    age: 31,
    address: "Shahdara",
    occupation: "Student",
  },
];
